#soon
def start_face
    puts '      '
    puts '      '
    puts '`-_   '
    puts '====\ '
    puts ' --.| '
    puts '  * ),'
    puts '\  / |'
    puts '---  |'
    puts '    #|'
    puts '   ##|'
    puts '--- / '
    puts '   (  '
    puts '   |  '
    puts '   |  '
    puts '  |   '
    puts ' .)   '
    puts '/     '
end

def next_face
    puts '        '
    puts '-,      '
    puts '==`-_   '
    puts '__====\ '
    puts ' . --.| '
    puts '(   * ),'
    puts ' \   / |'
    puts '\ ---  |'
    puts '_)    #|'
    puts '     ##|'
    puts '----- / '
    puts '     (  '
    puts '     |  '
    puts '     |  '
    puts '    |   '
    puts '   .)   '
    puts '==/     '
end

def next_face2
    puts '          '
    puts '`--,      '
    puts '====`-_   '
    puts '=___====\ '
    puts '.  . --.| '
    puts ') (   * ),'
    puts '/\ \   / |'
    puts '  \ ---  |'
    puts '___)    #|'
    puts '       ##|'
    puts '------- / '
    puts '       (  '
    puts '       |  '
    puts '       |  '
    puts '      |   '
    puts '.    .)   '
    puts '====/     '
end
#you better get ready to show me what you got
def next_face3
    puts '__          '
    puts '  `--,      '
    puts '======`-_   '
    puts '===___====\ '
    puts '--.  . --.| '
    puts '* ) (   * ),'
    puts '  /\ \   / |'
    puts '-   \ ---  |'
    puts '  ___)    #|'
    puts '         ##|'
    puts '--------- / '
    puts '         (  '
    puts '         |  '
    puts '         |  '
    puts '        |   '
    puts '##.    .)   '
    puts '======/     '
end

def next_face4
    puts ' ___          '
    puts '^   `--,      '
    puts '========`-_   '
    puts '-====___====\ '
    puts '- --.  . --.| '
    puts '  * ) (   * ),'
    puts '    /\ \   / |'
    puts '---   \ ---  |'
    puts '    ___)    #|'
    puts '           ##|'
    puts ' ---------- / '
    puts '           (  '
    puts '#          |  '
    puts '##         |  '
    puts '##        |   '
    puts '\###.    .)   '
    puts ' `======/     '
end

def next_face5
    puts '  ___          '
    puts '-^   `--,      '
    puts '=========`-_   '
    puts '--====___====\ '
    puts '.- --.  . --.| '
    puts '|  * ) (   * ),'
    puts '\    /\ \   / |'
    puts ' ---   \ ---  |'
    puts '     ___)    #|'
    puts '#           ##|'
    puts '# ---------- / '
    puts '#           (  '
    puts '##          |  '
    puts '###         |  '
    puts '\##        |   '
    puts ' \###.    .)   '
    puts '  `======/     '
end

def next_face6
    puts '       ___          '
    puts '   . -^   `--,      '
    puts '  /# =========`-_   '
    puts ' /# (--====___====\ '
    puts '/#   .- --.  . --.| '
    puts '##   |  * ) (   * ),'
    puts '##   \    /\ \   / |'
    puts '###   ---   \ ---  |'
    puts '####      ___)    #|'
    puts '######           ##|'
    puts '\##### ---------- / '
    puts ' \####           (  '
    puts '  `\###          |  '
    puts '    \###         |  '
    puts '     \##        |   '
    puts '      \###.    .)   '
    puts '       `======/     '
end

def on_screen
    puts '        ___          '
    puts '    . -^   `--,      '
    puts '   /# =========`-_   '
    puts '  /# (--====___====\ '
    puts ' /#   .- --.  . --.| '
    puts '/##   |  * ) (   * ),'
    puts '|##   \    /\ \   / |'
    puts '|###   ---   \ ---  |'
    puts '|####      ___)    #|'
    puts '|######           ##|'
    puts ' \##### ---------- / '
    puts '  \####           (  '
    puts '   `\###          |  '
    puts '     \###         |  '
    puts '      \##        |   '
    puts '       \###.    .)   '
    puts '        `======/     '
end
# SHOW ME WHAT YOU GOT
def open_mouth
    puts '        ___          '
    puts '    . -^   `--,      '
    puts '   /# =========`-_   '
    puts '  /# (--====___====\ '
    puts ' /#   .- --\  / --.| '
    puts '/##   |  * ) (   * ),'
    puts '|##   \    /\ \   / |'
    puts '|###   ---   \ ---  |'
    puts '|####      ___)    #|'
    puts '|######           ##|'
    puts ' \##### ---------- / '
    puts '  \#### \________/(  '
    puts '   `\###          |  '
    puts '     \###         |  '
    puts '      \##        |   '
    puts '       \###.    .)   '
    puts '        `======/     '
end
